baseURL = "https://lariojatech.org"
languageCode = "gl-es"
title = "La Rioja Tech Alliance"
publishDir = "docs"
theme = "hugoscroll"

[Params]
  github = "LaRioja-Tech-alliance"
  twitter = "lariojatech"
  email = "lariojatech@gmail.com"
  description = "Los grupos de tecnología de La Rioja hacemos piña para promover la tecnología"
  cover = "./images/bg.jpg"
  logo = "./images/riojatech-fondo-alliance.png"
