baseURL = "https://lariojatech.org"
languageCode = "gl-es"
title = "La Rioja Tech Alliance"
publishDir = "docs"
theme = "hugoscroll"

[Params]
  github = "LaRiojaTech"
  twitter = "GDGLaRioja"
  email = "alliance@vigotech.org"
  description = "La Rioja Tech Alliance, grupos de tecnología en La Rioja"
  cover = "/images/bg.jpg"
  logo = "/images/logo_white.jpg"
